services:
  ololo-gate-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_API_VERSION=${VITE_API_VERSION}
    container_name: ololo-gate-admin-container
    ports:
      - "4173:4173"
    env_file:
      - .env
    restart: unless-stopped
